### PR TITLE
Add Windows support

### PR DESCRIPTION
**Pull request by brunoyb**
This is an attempt to make git_scripts cross compatible with Windows (#37).

Most of the changes involves removing dependencies on Unix commands/idioms and changing quotations for system commands because Windows don't parse single quotes the same way as in Unix.

Thanks for the attention!

### CODE REVIEW

**Comment by brunoyb** [comment]
Hi! I couldn't find a way to configure a Windows environment on Travis so I just fixed the issues with what was already in place.

**Comment by zlu** [comment]
+1

**Comment by zlu** [comment]
I think we should keep this open, or fork it.

**Comment by brunoyb** [comment]
Yes, although I deleted my fork, the issue is still open (#37) and I'm guessing this PR can still work if reopened. But a fork is probably a better idea to keep the PR alive.

Also, I just read my comment from last year about configuring Travis... Recently I learned about AppVeyor, maybe it can be configured to run the test suite on Windows.

**Pull request closed without merging**
